#!/bin/bash


#Making configs folder and setting the path.
[ -d ~/.config/lgames ] || mkdir -p ~/.config/lgames

if [[ $1 == "-p" ]];then
	shift
	echo "$1" > ~/.config/lgames/games.txt
	echo "PATH HAS BEEN SET!"
fi

if [ ! -f "~/.config/lgame/path.txt" ];then 
	GAMES_DIR=$(<~/.config/lgames/path.txt)
fi

if [[ -n "$GAMES_DIR" ]]
then
	echo "Searching in the path: $GAMES_DIR"
	echo "If a game is not working, write 'pro' in order to use proton"
	sleep 2s
else
	echo -e "\e[37mpath.txt file is empty.\e[0m"
	echo "usage: lgame -p <path to the games/programes directory>"
	echo "the path is then stored in ~/.config/lgames/path.conf so you can call it again without an arguement"
	exit 1
fi

ls "$GAMES_DIR" > ~/.config/lgames/games.txt

games_count=$(wc -l < ~/.config/lgames/games.txt)
count=1
Game_path=""

create_list(){
	touch ~/.lgame.txt
	for (( i = count ; i <= games_count ; i++));
	do
		first_game=$( sed -n "$i p" ~/.config/lgames/games.txt )
		first_character=$( echo "$first_game" | cut -c 1 )

		#First try : search by full name
		Game_exe=$( find  "$GAMES_DIR/$first_game" -type f -iname "$first_game*.exe" -printf "%f\n" | sed -n "1p")


		#Searching by the first character.
		if [  -z "$Game_exe" ];then
			Game_exe=$( find "$GAMES_DIR"/"$first_game" -type f -iname "$first_character*.exe" -printf "%f\n" | sed -n "1p")
		fi
		#Getting the first .exe file found.
		if [ -z "$Game_exe" ];then
			Game_exe=$(find "$GAMES_DIR"/"$first_game" -type f -iname "*.exe" -printf "%f\n" | sort -t '\0' -n | sed -n "1 p")
		fi
		if [[ -z "$Game_exe" ]]
		then

			echo -e "\nCouldn't find the following game : $first_game\n-------------------------\n" >> ~/.lgame.txt
			games_count=$(( games_count - 1 ))
			continue
		fi

		local Game_path=$( find "$GAMES_DIR"/"$first_game" -type f -iname "$Game_exe" | sed -n "1p")
		echo -e "$Game_path\n[APP] : [$Game_exe]\n-------------------------\n" >> ~/.lgame.txt

	done
}

create_list

c_layer=wine


list_count=$(( $(wc -l ~/.lgame.txt | cut -d " " -f 1)/2 - 1 ))

#displaying the list found in ~/.lgame.txt
display_list(){
  clear
	DISPLAYED_GAMES=5
	if [[ $DISPLAYED_GAMES -ge $list_count ]];then
		DISPLAYED_GAMES=$list_count
	fi

	if [[ ! $(( DISPLAYED_GAMES % 2 )) -eq 0 ]];then
		if [[ $DISPLAYED_GAMES -gt 0 ]];then
			DISPLAYED_GAMES=$((DISPLAYED_GAMES-1))
		else
			DISPLAYED_GAMES=$((DISPLAYED_GAMES+1))
		fi
	fi

	local SAP=4 #space between apps
	local c=$(( SAP*count ))

	echo -e "\e[48;2;0;0;0m\e[1m"
	sed -n "$((c-2)) p" ~/.lgame.txt
	echo -e "\e[0m"

	sed -n "$(( c-1 )),$(( (DISPLAYED_GAMES*6) + c )) p" ~/.lgame.txt


	Game_path="$( sed -n "$((c-3)) p" ~/.lgame.txt)"
	echo -e "\nTotal_games: $games_count\ntype 'out' in order to exit"

}

Search(){

	local line_number=$( grep -i -n "$1" < ~/.lgame.txt | sed -n "1 p" | cut -d ":" -f 1)

	if [[ -z $line_number ]];then
		echo "GAME NOT FOUND!"
		sleep 1
		display_list
		return 
	fi

	Game=$(sed -n "$line_number,$(( line_number+2 )) p" ~/.lgame.txt)
	Game_path="$(sed -n "$line_number p" ~/.lgame.txt)"

	if [[ -n $Game ]];then
		clear
		echo "$Game"
		echo -e "GAME FOUND!\nPATH : $Game_path\nLAUNCHING..."
		game_dir=$(dirname "$Game_path")
		echo "$Game_path"
		cd "$game_dir"
		if [[ $c_layer == $proton ]];then
			"$c_layer" run "$Game_path"
			exit 0
		fi
		$c_layer "$Game_path"
		exit 0

	fi
}

display_list
tput civis
#trap "rm -rf ~/.lgame.txt && tput cnorm" EXIT

move(){
  case "$1" in
    "up")
			if [[ $count -gt 1 ]];then
				count=$(( (count - 1) ))
				display_list
			fi
      ;;
    "down")
			if [[ $count -lt $games_count ]];then

				count=$(( count + 1 ))
				display_list
			fi
      ;;
  esac

}

read_input(){
  read -rsn1 char
  case $char in
    $'\0')
      echo "STARTING THE GAME"
      game_dir=$(dirname "$Game_path")
      cd "$game_dir"
      if [[ $c_layer == $proton ]];then
        "$c_layer" run "$Game_path"
        exit 0
      fi
      $c_layer "$Game_path"
      exit 0
      ;;
    $'\e')
      read -rsn1 char
      if [[ $char == '[' ]];then
        read -rsn1 char
        case $char in
          'A')
            move "up"
            ;;
          'B')
            move "down"
            ;;
        esac
      fi
      ;;
    '/')
      write_mode
      printf "/"
      read -r char
      display_list
	    char=$(echo "$char" | tr "[:upper:]" "[:lower:]")
      read_options "$char"
      ;;

    esac
}

write_mode(){
  printf "\x1b[?25h\x1b[$(tput lines);0f"
}
reset_mode(){
  printf "\x1b[?25h\x1b[$(( $(tput lines)-1 ));0f\x1b[0J"
}

read_options(){
  case "$1" in
		$'exit')
      exit 0
			;;
		$'search')
			echo "Starting Search : "
			read -r term
			Search "$term";;
		$'proton')
			if [[ -d ~/.steam ]];then
				proton=$(find ~/.steam/root/steamapps/common -name "proton" | sed -n "1 p")
			else
				echo "steam folder wasn't found, is steam installed?"
				exit 1
			fi
			if [[ -z $proton ]];then
				echo "Proton wasn't found, please check if it is installed"
				exit 1
			fi
			echo "Changing to proton"
			mkdir -p ~/.steam/steam/steamapps/compatdata/shared_prefix
			export STEAM_COMPAT_DATA_PATH=~/.steam/steam/steamapps/compatdata/shared_prefix
			export STEAM_COMPAT_CLIENT_INSTALL_PATH=~/.steam/root
			c_layer="$proton";;
		$'wine')
			echo "Changing to wine"
			c_layer=wine;;
		$'refresh')
			create_list
			display_list
			;;
    esac
}

#The main loop

while :
do
  read_input
done
